name=KeyboardUTF8
version=1.0.0
author=JohnWasser
maintainer=JohnWasser <Arduino@John-Wasser.com>
sentence=Adds non-US keyboard layouts and UTF-8 (Unicode) to TinyUSB keyboard for ESP32S3.
paragraph=This library provides mapping for non-US keyboards and non-ASCII (Unicode) characters in UTF-8 format for ESP32S3 boards using TinyUSB. It uses keyboard layout data scraped from Microsoft's globalization website.
category=Device Control
url=https://github.com/JohnWasser/Arduino_KeyboardUTF8
architectures=esp32
